#!/bin/bash

exec brew install coreutils binutils diffutils ed findutils gawk gnu-indent gnu-sed gnu-tar gnu-which gnutls grep gzip screen tmux watch wdiff curl wget git python less openssh rsync unzip vim bash lynx gpg gh pandoc nmap shellcheck shfmt entr bash-completion yt-dlp tree neovim font-ubuntu-mono-nerd-font wezterm
