#!/bin/bash

brew install tmux watch wdiff curl wget git python less openssh rsync unzip vim bash lynx gpg gh pandoc shellcheck shfmt bash-completion fzf tree neovim font-ubuntu-mono-nerd-font || exit $?

exec brew install --cask wezterm obsidian rustdesk telegram spotify chatgpt zen viz pearcleaner
