#!/bin/bash

font_dir="$HOME/.fonts"
font_archive=$(mktemp)

trap 'rm -f "$font_archive"' EXIT HUP INT TERM

mkdir -p "$font_dir/UbuntuMonoNerdFont"
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/UbuntuMono.zip -O "$font_archive"
unzip -oq "$font_archive" -d "$font_dir/UbuntuMonoNerdFont"
fc-cache -f
