#!/usr/bin/env bash

set -e

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH='' cd -- "$script_dir/../.." && pwd)

"$script_dir/install-with-apt"
"$script_dir/install-ubuntu-mono-font"
"$script_dir/install-wezterm"
"$repo_dir/wezterm/setup"
