let g:skip_defaults_vim = 1

set nocompatible

set autoindent
set expandtab
set tabstop=2
" for >> and << 
set shiftwidth=2

set hlsearch
set incsearch
set noignorecase

set textwidth=72

set ruler
set showmode
set laststatus=0

set noerrorbells
set visualbell
set t_vb=

set linebreak
set wrapscan
set nowrap

if has ("syntax")
  syntax on
endif

filetype plugin on

set nobackup
set noswapfile
set nowritebackup

set ruf=%30(%=%#LineNr#%.50F\ [%{strlen(&ft)?&ft:'none'}]\ %l:%c\ %p%%%)


nnoremap <C-L> :nohl<CR><C-L>

call plug#begin()

  Plug 'dense-analysis/ale'
  Plug 'sainnhe/gruvbox-material'

call plug#end()

colorscheme gruvbox-material

let g:ale_set_highlights = 0
let g:ale_sign_error = '☠️'
let g:ale_sign_warning = '⚠️'

highlight Normal ctermbg=NONE
highlight ModeMsg ctermbg=NONE ctermfg=238
highlight Comment ctermbg=NONE ctermfg=238
highlight StatusLine ctermbg=NONE ctermfg=238
highlight StatusLineNC ctermbg=NONE ctermfg=238
highlight LineNr ctermbg=NONE ctermfg=238
highlight Search ctermbg=black ctermfg=darkred
highlight MatchParen ctermbg=black ctermfg=darkred
highlight IncSearch ctermbg=black ctermfg=darkred
highlight VirtualTextError ctermbg=NONE ctermfg=238
highlight VirtualTextWarning ctermbg=NONE ctermfg=238
highlight VirtualTextInfo ctermbg=NONE ctermfg=238
highlight VirtualTextHint ctermbg=NONE ctermfg=238

au ColorScheme * highlight Normal ctermbg=NONE
au ColorScheme * highlight StatusLine ctermbg=NONE ctermfg=238
au ColorScheme * highlight StatusLineNC ctermbg=NONE ctermfg=238
au ColorScheme * highlight LineNr ctermbg=NONE ctermfg=238
au ColorScheme * highlight ModeMsg ctermbg=NONE ctermfg=238
au ColorScheme * highlight Comment ctermbg=NONE ctermfg=238
au ColorScheme * highlight Search ctermbg=black ctermfg=darkred
au ColorScheme * highlight IncSearch ctermbg=black ctermfg=darkred
au ColorScheme * highlight MatchParen ctermbg=black ctermfg=darkred
au ColorScheme * highlight VirtualTextError ctermbg=NONE ctermfg=238
au ColorScheme * highlight VirtualTextWarning ctermbg=NONE ctermfg=238
au ColorScheme * highlight VirtualTextInfo ctermbg=NONE ctermfg=238
au ColorScheme * highlight VirtualTextHint ctermbg=NONE ctermfg=238

set wrap
