#!/bin/sh

set -e

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)

mkdir -p "$HOME/Scripts"
for script in duck lynx urlencode vic; do
	ln -sf "$script_dir/$script" "$HOME/Scripts/$script"
done
